### ISSUE TITLE
Enable Animated Emotes Switch in Player

### ISSUE THREAD

**Issue by FoseFx** [bttv-android/bttv#213]
If there is no actual fix possible for the foreseeable future for this issue, would it be possible to add the animated/static toggle somewhere in the player settings (gear in top right of the video player) so it is something that could be easily toggled while watching the stream instead of digging into the app settings every time?

As you found, the problem is dependent on the BTTV usage of the channel. The idea is to be able to quickly toggle between static and animated on a per stream basis and I think this would significantly help mitigate the issue as much as possible for now.

_Originally posted by @Jfamig in https://github.com/bttv-android/bttv/issues/152#issuecomment-887978726_

**Comment by Jfamig** [comment]
Just a quick amendment: there is now a button with 3 vertical dots on the bottom right of the chat containing a few chat related options such as chat identity and the offensive language filter.

This may be a more appropriate location for the animated/static emote toggle instead of the player settings.
