### ISSUE TITLE
Improve the speed of deletion

### ISSUE THREAD

**Issue by M1B4ND** [bttv-android/bttv#334]
![Screenshot_20211201-205803](https://user-images.githubusercontent.com/70129787/144305806-9c24f50e-b263-4cb8-b4e2-3c6f68cc3721.png)

I propose to improve the button that deletes the text we wrote.
Keeping it pressed, let it erase the text faster because currently it does not and many applications use this long press for that.
And I find that it would be really useful especially when we want to send emotes it will be useful.
Because when you write text you have deletion available on your keyboard but suddenly you don't have it when you just want to send emoticons.

**Comment by FoseFx** [comment]
I totally get that this is annoying, but too keep the mod stable it's changes to the twitch app should be minimal. I'd like to see this as well, but messing with the input behavior likely leads to hard-to-debug issues, that's why I don't think this is feasible to implement for this project.

Try to reach out to twoch over https://twitch.uservoice.com/ instead, and thank you for your interest in this project!
