### ISSUE TITLE
BTTV and Watch Partys

### ISSUE THREAD

**Issue by NumbPat** [bttv-android/bttv#367]
So with the latest Update on v.0.18.0, you put a "Watch Party fix" in the patch notes.
I was wondering how you've done that and today I got the opportunity to look what kind of patch this is.

A new pop up screen with an introduction how to use BTTV and Amazon Prime Video showing up on screen. It says,that you have to download the OG Twitch App in order to watch the Party on the BTTV App. I followed the other introductions and was excited. For a short time.

Now,when I open a stream,I get the message that I have to connect my Amazon Prime with Twitch. 
What I already did.
But the problem now is,when I tap on that message,it does nothing. I just can tap on it, but thats it.
I've tried to have both apps, BTTV & the OG App, parallel open. But it doesn't worked either.

I don't know if I misunderstood the "fix" message (if yes I'm totally sorry for putting an Issue for it), like to patch the infinite loop, but I followed your introduction and it still doesn't work. 
At least for me.
It's even showing me in the BTTV App, that I'm able to log out from Amazon Prime.

Have I done something wrong?

**Comment by FoseFx** [comment]
First of all: Thank you for the bug report!

I logged out to try it out again and had the same behavior you described, so I tried it out on an emulator and it worked.
Turns out there is an issue, when a) a "first party" app (e.g. Amazon Video, Amazon Shopping, ...) is installed on the device and b) you tried to log in before.

I [fixed](https://github.com/bttv-android/bttv/commit/355707c8253f62852fcc40119675f1ef3d64e817) this by bypassing the detection on first party Apps entirely, so bttv-android will always launch the browser.

It's all a bit confusing right now and I hope I can get rid of the dependence of the Twitch App in the near future.

Please re-open this when you still encounter this issue after the next version is released.

**Comment by NumbPat** [comment]
Thank you so much for responding.
Love your App and your efforts you put into this project! I'm very grateful.

I will definitely giving you feedback if it's happening again after your patch.

**Comment by FoseFx** [comment]
@all-contributors please add @NumbPat for bugs

**Comment by NumbPat** [comment]
Won't reopen the Issue, just wanted to inform you, that your latest patch worked.
A little bit buggy, but it's working. 
I have to close my browser and reopen the BTTV App to make it work. 
So the browser,at least for me, have to be completely closed to prevent an infinite loop or a black screen. 
But thank you very much for your patch!
