### ISSUE TITLE
Can not log in

### ISSUE THREAD

**Issue by framerunner** [bttv-android/bttv#588]
### Existing Issues

- [X] I have searched for existing issues, this is not a duplicate.

### Unmodded Twitch

- [x] I have checked and this issue only occurs using bttv-android and not with the unmodded Twitch App

### What happened?

I recommended the app to someone, who then tried to log in but couldn't.
After logging out myself on the app and trying to log back in, I got the message
"Oops! We encountered an unexpected error. Please try again."

### bttv-android version

v0.35.1-beta

### android version

11

### device

Moto G 10

### Anything else?

I can confirm that the exact same logins work on the unmodded Twitch App and in my browser.
I use a password manager, so errors in typing are not a possible.

**Comment by Benderosy** [comment]
I'm having the same issue.

**Comment by LtHusky1218** [comment]
same here, even with the old version still can't login

**Comment by FoseFx** [comment]
Turns out the `passport.twitch.tv` backend started failing integrity checks (I think this has something to do with rate-limiting) for "invalid" User-Agents.
This is a marvelously bad idea, as it is [easy to circumvent](https://github.com/bttv-android/bttv/pull/589/commits/52262cc54c32bc060ad7e51c50b9375ea4bfbdf3) and makes it impossible for other clients to identify themselves towards the server.
It also cost me my morning trying to find this out. Thank you Twitch!

Fix will be released probably tomorrow or the day after as I'm very short on time right now.

**Comment by HuntertheSquirrel** [comment]
It happened to me too....
This app needs to be patched soon.

**Comment by FoseFx** [comment]
It's already patched! You maybe need to manually download the new version, I'm not sure if the banner shows up when the user is not signed in.
