### ISSUE TITLE
App crash after update

### ISSUE THREAD

**Issue by zeykafx** [bttv-android/bttv#85]
after updating the app to 0.6.0 beta the app crashes when opening (even with a fresh install).

**Comment by TheSpartaPT** [comment]
Same, I'm on Android 11

**Comment by FoseFx** [comment]
Thank you so much for the reports! ❤️ 
I can confirm this and stopped the update.

A fix is tracked by #86

Postmortem:
A recent update of the base has caused a reduction of dex files (11 -> 6). All bttv-android classes are stored in a new dex file (smali_classes12). Apktool did not find the classes as it stopped after not finding smali_classes7.

This bug was not caught as smali_classes7-11 still existed in my testing environment.

**Comment by FoseFx** [comment]
[v0.6.1-beta](https://github.com/bttv-android/bttv/releases/tag/v0.6.1-beta) was just released and confirmed working!

**Comment by zeykafx** [comment]
It's working fine for me too! Thanks for the quick fix!

**Comment by FoseFx** [comment]
@all-contributors please add @zeykafx for bug
